# Generated by Django 5.0.6 on 2025-10-16 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('work_description', models.TextField()),
                ('truck', models.CharField(choices=[('hino_24', 'Hino24'), ('international_24', 'International24'), ('freightliner_26', 'Freightliner26'), ('hino_26', 'Hino26')], max_length=20)),
                ('truck_mileage', models.PositiveIntegerField()),
                ('truck_fuel_level', models.CharField(choices=[('empty', 'Empty'), ('quarter', '1/4'), ('half', '1/2'), ('three_quarters', '3/4'), ('full', 'Full')], max_length=20)),
                ('def_level', models.CharField(choices=[('empty', 'Empty'), ('quarter', '1/4'), ('half', '1/2'), ('three_quarters', '3/4'), ('full', 'Full')], max_length=20)),
                ('thermoking_hours', models.PositiveIntegerField()),
                ('error_lights_faults', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airway_bill', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('small', 'Small'), ('large', 'Large'), ('other', 'Other')], default='small', max_length=20)),
                ('amount_small', models.PositiveIntegerField(default=0, verbose_name='Small Items Count')),
                ('amount_large', models.PositiveIntegerField(default=0, verbose_name='Large Items Count')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='logs.driverlog')),
            ],
            options={
                'ordering': ['airway_bill', 'item_type'],
            },
        ),
        migrations.CreateModel(
            name='ThermoKingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('thermoking_front', 'ThermoKing Front'), ('thermoking_side', 'ThermoKing Side'), ('thermoking_controls', 'ThermoKing Controls')], max_length=20)),
                ('image', models.ImageField(upload_to='thermoking_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thermoking_images', to='logs.driverlog')),
            ],
        ),
        migrations.CreateModel(
            name='TruckChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lights', models.CharField(choices=[('ok', 'OK'), ('needs_attention', 'Needs Attention'), ('not_applicable', 'N/A')], default='ok', max_length=20)),
                ('mirrors', models.CharField(choices=[('ok', 'OK'), ('needs_attention', 'Needs Attention'), ('not_applicable', 'N/A')], default='ok', max_length=20)),
                ('tires', models.CharField(choices=[('ok', 'OK'), ('needs_attention', 'Needs Attention'), ('not_applicable', 'N/A')], default='ok', max_length=20)),
                ('brakes', models.CharField(choices=[('ok', 'OK'), ('needs_attention', 'Needs Attention'), ('not_applicable', 'N/A')], default='ok', max_length=20)),
                ('suspension_check', models.CharField(choices=[('ok', 'OK'), ('needs_attention', 'Needs Attention'), ('not_applicable', 'N/A')], default='ok', max_length=20)),
                ('pallet_jack', models.CharField(choices=[('ok', 'OK'), ('needs_attention', 'Needs Attention'), ('not_applicable', 'N/A')], default='ok', max_length=20)),
                ('shrink_wrap', models.CharField(choices=[('ok', 'OK'), ('needs_attention', 'Needs Attention'), ('not_applicable', 'N/A')], default='ok', max_length=20)),
                ('pallets', models.CharField(choices=[('ok', 'OK'), ('needs_attention', 'Needs Attention'), ('not_applicable', 'N/A')], default='ok', max_length=20)),
                ('def_fluid', models.CharField(choices=[('ok', 'OK'), ('needs_attention', 'Needs Attention'), ('not_applicable', 'N/A')], default='ok', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='logs.driverlog')),
            ],
        ),
        migrations.CreateModel(
            name='TruckImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('truck_front', 'Truck Front'), ('truck_back', 'Truck Back'), ('truck_left', 'Truck Left'), ('truck_right', 'Truck Right'), ('truck_interior', 'Truck Interior'), ('truck_dashboard', 'Truck Dashboard')], max_length=20)),
                ('image', models.ImageField(upload_to='truck_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck_images', to='logs.driverlog')),
            ],
        ),
    ]
